name: Validate Features

on:
  pull_request:
    paths:
      - "features/src/**/devcontainer-feature.json"
      - ".github/workflows/validate.yml"

permissions:
  contents: read

jobs:
  validate:
    name: Validate devcontainer-feature.json files
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Validate devcontainer-feature.json files
        uses: devcontainers/action@1082abd5d2bf3a11abccba70eef98df068277772 # v1.4.3
        with:
          validate-only: "true"
          base-path-to-features: "./features/src"
